/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_flowvisor_log_Syslog */

#ifndef _Included_org_flowvisor_log_Syslog
#define _Included_org_flowvisor_log_Syslog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_flowvisor_log_Syslog
 * Method:    open
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_flowvisor_log_Syslog_open
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_flowvisor_log_Syslog
 * Method:    log
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_flowvisor_log_Syslog_log
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
